project:
  type: website
  output-dir: _site

author: HPDell

website:
  title: "Python For Her"
  sidebar:
    contents: 
      - text: 简介
        file: index.qmd
      - section: Python 基础
        contents: 01-Basics/*
  page-navigation: true

format:
  html:
    theme:
      dark: darkly
      light: flatly
    number-sections: true
    toc: true
  revealjs:
    theme: night
    chalkboard: true
    width: 1200
    height: 700
    output-ext: slides.html

lang: zh

execute: 
  echo: true
  freeze: auto

